### ISSUE TITLE
Не получается запустить локально после очередного обновления

### ISSUE THREAD

**Issue by zerotool** [noff/snek#89]
Как я понимаю, не хватает переменных окружения, либо конфигурационных файлов локальных:

```/Users/stan/.rvm/rubies/ruby-2.3.1/bin/ruby -e $stdout.sync=true;$stderr.sync=true;load($0=ARGV.shift) /Applications/mampstack-5.6.24-0/apps/snek/bin/rails server -b 0.0.0.0 -p 3000 -e development
=> Booting Puma
=> Rails 5.2.0 application starting in development 
=> Run `rails server -h` for more startup options
Exiting
/Applications/mampstack-5.6.24-0/apps/snek/config/initializers/rollbar.rb:5:in `block in <main>': undefined method `[]' for nil:NilClass (NoMethodError)
	from /Users/stan/.rvm/gems/ruby-2.3.1/gems/rollbar-2.16.0/lib/rollbar/notifier.rb:51:in `configure'
	from /Users/stan/.rvm/gems/ruby-2.3.1/gems/rollbar-2.16.0/lib/rollbar.rb:67:in `configure'
	from /Applications/mampstack-5.6.24-0/apps/snek/config/initializers/rollbar.rb:1:in `<main>'
	from /Users/stan/.rvm/gems/ruby-2.3.1/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
	from /Users/stan/.rvm/gems/ruby-2.3.1/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
	from /Users/stan/.rvm/gems/ruby-2.3.1/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:277:in `block in load'
	from /Users/stan/.rvm/gems/ruby-2.3.1/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:249:in `load_dependency'
	from /Users/stan/.rvm/gems/ruby-2.3.1/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:277:in `load'
	from /Users/stan/.rvm/gems/ruby-2.3.1/gems/railties-5.2.0/lib/rails/engine.rb:657:in `block in load_config_initializer'
	from /Users/stan/.rvm/gems/ruby-2.3.1/gems/activesupport-5.2.0/lib/active_support/notifications.rb:170:in `instrument'
	from /Users/stan/.rvm/gems/ruby-2.3.1/gems/railties-5.2.0/lib/rails/engine.rb:656:in `load_config_initializer'
	from /Users/stan/.rvm/gems/ruby-2.3.1/gems/railties-5.2.0/lib/rails/engine.rb:614:in `block (2 levels) in <class:Engine>'
	from /Users/stan/.rvm/gems/ruby-2.3.1/gems/railties-5.2.0/lib/rails/engine.rb:613:in `each'
	from /Users/stan/.rvm/gems/ruby-2.3.1/gems/railties-5.2.0/lib/rails/engine.rb:613:in `block in <class:Engine>'
	from /Users/stan/.rvm/gems/ruby-2.3.1/gems/railties-5.2.0/lib/rails/initializable.rb:32:in `instance_exec'
	from /Users/stan/.rvm/gems/ruby-2.3.1/gems/railties-5.2.0/lib/rails/initializable.rb:32:in `run'
	from /Users/stan/.rvm/gems/ruby-2.3.1/gems/railties-5.2.0/lib/rails/initializable.rb:61:in `block in run_initializers'
	from /Users/stan/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
	from /Users/stan/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /Users/stan/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
	from /Users/stan/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /Users/stan/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
	from /Users/stan/.rvm/gems/ruby-2.3.1/gems/railties-5.2.0/lib/rails/initializable.rb:50:in `each'
	from /Users/stan/.rvm/gems/ruby-2.3.1/gems/railties-5.2.0/lib/rails/initializable.rb:50:in `tsort_each_child'
	from /Users/stan/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:415:in `call'
	from /Users/stan/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:415:in `each_strongly_connected_component_from'
	from /Users/stan/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /Users/stan/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `each'
	from /Users/stan/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `call'
	from /Users/stan/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
	from /Users/stan/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
	from /Users/stan/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
	from /Users/stan/.rvm/gems/ruby-2.3.1/gems/railties-5.2.0/lib/rails/initializable.rb:60:in `run_initializers'
	from /Users/stan/.rvm/gems/ruby-2.3.1/gems/railties-5.2.0/lib/rails/application.rb:361:in `initialize!'
	from /Applications/mampstack-5.6.24-0/apps/snek/config/environment.rb:5:in `<main>'
	from /Users/stan/.rvm/gems/ruby-2.3.1/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
	from /Users/stan/.rvm/gems/ruby-2.3.1/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
	from /Users/stan/.rvm/gems/ruby-2.3.1/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
	from /Users/stan/.rvm/gems/ruby-2.3.1/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
	from /Users/stan/.rvm/gems/ruby-2.3.1/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
	from /Users/stan/.rvm/gems/ruby-2.3.1/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `block in require'
	from /Users/stan/.rvm/gems/ruby-2.3.1/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:249:in `load_dependency'
	from /Users/stan/.rvm/gems/ruby-2.3.1/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `require'
	from /Users/stan/.rvm/gems/ruby-2.3.1/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:44:in `require_relative'
	from config.ru:3:in `block in <main>'
	from /Users/stan/.rvm/gems/ruby-2.3.1/gems/rack-2.0.5/lib/rack/builder.rb:55:in `instance_eval'
	from /Users/stan/.rvm/gems/ruby-2.3.1/gems/rack-2.0.5/lib/rack/builder.rb:55:in `initialize'
	from config.ru:in `new'
	from config.ru:in `<main>'
	from /Users/stan/.rvm/gems/ruby-2.3.1/gems/rack-2.0.5/lib/rack/builder.rb:49:in `eval'
	from /Users/stan/.rvm/gems/ruby-2.3.1/gems/rack-2.0.5/lib/rack/builder.rb:49:in `new_from_string'
	from /Users/stan/.rvm/gems/ruby-2.3.1/gems/rack-2.0.5/lib/rack/builder.rb:40:in `parse_file'
	from /Users/stan/.rvm/gems/ruby-2.3.1/gems/rack-2.0.5/lib/rack/server.rb:319:in `build_app_and_options_from_config'
	from /Users/stan/.rvm/gems/ruby-2.3.1/gems/rack-2.0.5/lib/rack/server.rb:219:in `app'
	from /Users/stan/.rvm/gems/ruby-2.3.1/gems/railties-5.2.0/lib/rails/commands/server/server_command.rb:27:in `app'
	from /Users/stan/.rvm/gems/ruby-2.3.1/gems/rack-2.0.5/lib/rack/server.rb:354:in `wrapped_app'
	from /Users/stan/.rvm/gems/ruby-2.3.1/gems/railties-5.2.0/lib/rails/commands/server/server_command.rb:89:in `log_to_stdout'
	from /Users/stan/.rvm/gems/ruby-2.3.1/gems/railties-5.2.0/lib/rails/commands/server/server_command.rb:51:in `start'
	from /Users/stan/.rvm/gems/ruby-2.3.1/gems/railties-5.2.0/lib/rails/commands/server/server_command.rb:147:in `block in perform'
	from /Users/stan/.rvm/gems/ruby-2.3.1/gems/railties-5.2.0/lib/rails/commands/server/server_command.rb:142:in `tap'
	from /Users/stan/.rvm/gems/ruby-2.3.1/gems/railties-5.2.0/lib/rails/commands/server/server_command.rb:142:in `perform'
	from /Users/stan/.rvm/gems/ruby-2.3.1/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /Users/stan/.rvm/gems/ruby-2.3.1/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/stan/.rvm/gems/ruby-2.3.1/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /Users/stan/.rvm/gems/ruby-2.3.1/gems/railties-5.2.0/lib/rails/command/base.rb:65:in `perform'
	from /Users/stan/.rvm/gems/ruby-2.3.1/gems/railties-5.2.0/lib/rails/command.rb:46:in `invoke'
	from /Users/stan/.rvm/gems/ruby-2.3.1/gems/railties-5.2.0/lib/rails/commands.rb:18:in `<main>'
	from /Users/stan/.rvm/gems/ruby-2.3.1/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
	from /Users/stan/.rvm/gems/ruby-2.3.1/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
	from /Users/stan/.rvm/gems/ruby-2.3.1/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
	from /Users/stan/.rvm/gems/ruby-2.3.1/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
	from /Users/stan/.rvm/gems/ruby-2.3.1/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
	from /Users/stan/.rvm/gems/ruby-2.3.1/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `block in require'
	from /Users/stan/.rvm/gems/ruby-2.3.1/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:249:in `load_dependency'
	from /Users/stan/.rvm/gems/ruby-2.3.1/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `require'
	from /Applications/mampstack-5.6.24-0/apps/snek/bin/rails:9:in `<top (required)>'
	from -e:1:in `load'
	from -e:1:in `<main>'

Process finished with exit code 1
```

**Comment by noff** [comment]
Так, это я добавлял кучу новых ключей в хранилище.
Давай через почту попробуем

выполни в консоли:
```EDITOR=nano rails credentials:edit```
что там написано? Вышли в почту.
